version: '3'
services:
  hook:
    build: .
    volumes:
      - ./hook:/hookdata
    hostname: hook

  runner:
    image: gitlab/gitlab-runner:latest
    volumes:
      - ./gitlab/runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5050:5050"
    depends_on:
      - gitlab
    hostname: runner

  gitlab:
    image: gitlab/gitlab-ce:12.4.2-ce.0
    ports:
      - "4430:443"
      - "8080:80"
      - "2222:22"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    depends_on:
      - hook
    hostname: gitlab
