version: '3'
services:
  hook:
    build: .
    volumes:
      - ./hook:/hookdata

  gitlab:
    image: gitlab/gitlab-ce:12.4.2-ce.0
    ports:
      - "4430:443"
      - "8080:80"
      - "2222:22"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    depends_on:
      - hook
